# -*- coding: utf-8 -*-
"""ADS_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FAkETcXtKWpNHUM-078hjbHNAccE0hz9

### 1.LOAD & MERGE DATA
"""

import pandas as pd
import numpy as np
import os

all_dfs = []

for file in os.listdir():
    if file.endswith(".csv"):
        country = file[:2].upper()
        try:
            df_temp = pd.read_csv(file, encoding="utf-8")
        except:
            df_temp = pd.read_csv(file, encoding="latin1")

        df_temp["country"] = country
        all_dfs.append(df_temp)

df = pd.concat(all_dfs, ignore_index=True)
print("Dataset Shape:", df.shape)

"""### 2.LANGUAGE ASSIGNMENT"""

def assign_language(row):
    if row["country"] == "IN":
        return np.random.choice(["Hindi", "Telugu", "Tamil", "English"])
    elif row["country"] == "US":
        return "English"
    elif row["country"] == "JP":
        return "Japanese"
    elif row["country"] == "KR":
        return "Korean"
    elif row["country"] == "RU":
        return "Russian"
    elif row["country"] == "FR":
        return "French"
    elif row["country"] == "DE":
        return "German"
    elif row["country"] == "MX":
        return "Spanish"
    else:
        return np.random.choice(["English", "Hindi", "Spanish", "French"])

df["language"] = df.apply(assign_language, axis=1)
print(df["language"].value_counts())

"""### 3. USER BEHAVIOR"""

df["user_id"] = np.random.randint(1, 1000, size=len(df))
df["video_duration"] = np.random.randint(60, 1200, size=len(df))
df["watch_time"] = np.random.randint(10, df["video_duration"])
df["watch_percentage"] = df["watch_time"] / df["video_duration"]

if "likes" in df.columns and "dislikes" in df.columns:
    df["liked"] = (df["likes"] > df["dislikes"]).astype(int)
else:
    df["liked"] = np.random.choice([0, 1], size=len(df))

df["skipped"] = (df["watch_percentage"] < 0.2).astype(int)

"""### 4. FEATURE ENGINEERING"""

df.fillna(0, inplace=True)

df["engagement_score"] = (
    0.6 * df["watch_percentage"] +
    0.3 * df["liked"] -
    0.2 * df["skipped"]
)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[["watch_time", "video_duration", "watch_percentage"]] = scaler.fit_transform(
    df[["watch_time", "video_duration", "watch_percentage"]]
)

"""### 5. USER-LEVEL DATA"""

user_features = df.groupby("user_id").agg({
    "watch_time": "mean",
    "watch_percentage": "mean",
    "engagement_score": "mean",
    "liked": "mean"
}).reset_index()

user_lang = df.groupby(["user_id", "language"])["watch_time"].sum().reset_index()

user_pref = user_lang.loc[
    user_lang.groupby("user_id")["watch_time"].idxmax()
]

user_data = user_features.merge(
    user_pref[["user_id", "language"]],
    on="user_id"
)

"""### 6. MODEL TRAINING"""

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

le = LabelEncoder()
user_data["language_encoded"] = le.fit_transform(user_data["language"])

features = ["watch_time", "watch_percentage", "engagement_score", "liked"]
counts = user_data["language_encoded"].value_counts()

valid_classes = counts[counts > 10].index

user_data = user_data[user_data["language_encoded"].isin(valid_classes)]

X = user_data[features]
y = user_data["language_encoded"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

models = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "Random Forest": RandomForestClassifier(class_weight="balanced"),
    "Naive Bayes": GaussianNB()
}

best_model = None
best_score = 0

for name, m in models.items():
    m.fit(X_train, y_train)
    preds = m.predict(X_test)

    acc = accuracy_score(y_test, preds)
    print(f"\n{name} Accuracy: {acc:.4f}")

    if acc > best_score:
        best_score = acc
        best_model = m

# final selected model
model = best_model

print("\nBest Model Selected:", model)
preds = model.predict(X_test)
print(classification_report(y_test, preds, zero_division=0))

"""### 7. PREDICTION"""

def predict_user(model, user_input, le):
    input_df = pd.DataFrame([user_input], columns=features)

    pred = model.predict(input_df)
    prob = model.predict_proba(input_df)

    return le.inverse_transform(pred)[0], max(prob[0])


sample_user = X_test.iloc[0].tolist()
lang, prob = predict_user(model, sample_user, le)

print("Predicted Language:", lang)
print("Confidence:", prob)

"""### 8.TOP-K PREDICTION"""

def predict_top_k(model, user_input, le, k=2):
    input_df = pd.DataFrame([user_input], columns=features)

    probs = model.predict_proba(input_df)[0]
    top_k = probs.argsort()[-k:][::-1]

    langs = le.inverse_transform(top_k)
    confs = probs[top_k]

    return list(zip(langs, confs))


print("Top 2:", predict_top_k(model, sample_user, le))

"""### 9. RECOMMENDATION"""

def recommend(df, language, top_n=5):
    recs = df[df["language"] == language].copy()
    recs = recs.sort_values(by="engagement_score", ascending=False).head(top_n)
    return recs[["video_id", "language", "engagement_score"]]


print("\nRecommendations:")
print(recommend(df, lang))

import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(le, open("label_encoder.pkl", "wb"))

df.to_csv("final_dataset.csv", index=False)